app:
    image: freecodecamp/mail-for-good:latest
    env_file: .env
    environment:
        - PSQL_USERNAME=postgres
        - PSQL_DATABASE=postgres
        - PSQL_HOST=postgres
        - REDIS_HOST=redis
        - VIRTUAL_HOST=app
        - VIRTUAL_PORT=8080
    links: 
        - redis
        - postgres

nginx:
    image: jwilder/nginx-proxy
    ports:
        - 80:80
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
        - app
    environment:
        - DEFAULT_HOST=app

postgres:
    image: postgres:latest

redis:
    image: redis:latest
